import type { Chain, RuleConfig, Scenario } from "./types";

export const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export const SAMPLE_ADDRESSES: Record<Chain, string> = {
  ethereum: "0xFEB4acf3df3cDEA7399794D0869ef76A6EfAff52",
  solana: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM",
};

export const CHAIN_CONFIG: Record<Chain, { name: string; placeholder: string; label: string }> = {
  ethereum: { name: "Ethereum", placeholder: "0x...", label: "Wallet Address" },
  solana: { name: "Solana", placeholder: "Base58 address...", label: "Solana Wallet Address" },
};

export const RULE_CONFIGS: RuleConfig[] = [
  {
    type: "allocation_cap",
    name: "Single-Token Concentration",
    description: "No single token should exceed this percentage of total portfolio value.",
    rationale: "Most treasury frameworks cap single-token allocation at 25-35% to prevent catastrophic loss from one asset crashing.",
    paramKey: "max_percent",
    paramLabel: "Max % per token",
    defaultValue: 30,
    min: 10,
    max: 80,
    step: 5,
    unit: "%",
    severity: "breach",
  },
  {
    type: "stablecoin_floor",
    name: "Stablecoin Minimum",
    description: "Stablecoins must represent at least this percentage of the portfolio.",
    rationale: "Maintaining 15-25% in stablecoins ensures 3-6 months of operating runway without forced liquidation during market downturns.",
    paramKey: "min_percent",
    paramLabel: "Min % in stablecoins",
    defaultValue: 20,
    min: 5,
    max: 60,
    step: 5,
    unit: "%",
    severity: "breach",
  },
  {
    type: "single_asset_cap",
    name: "Absolute Asset Cap",
    description: "No single asset should exceed this absolute USD value.",
    rationale: "Absolute caps prevent over-exposure even when percentage rules pass. Limits maximum loss from a single token collapse.",
    paramKey: "max_usd",
    paramLabel: "Max USD per asset",
    defaultValue: 500000,
    min: 50000,
    max: 5000000,
    step: 50000,
    unit: "$",
    severity: "warning",
  },
  {
    type: "max_tx_size",
    name: "Transaction Size Limit",
    description: "No single transaction should exceed this USD value.",
    rationale: "Spending guardrails prevent unauthorized or accidental large transfers. Most treasuries set this at 5-15% of total holdings.",
    paramKey: "max_usd",
    paramLabel: "Max USD per transaction",
    defaultValue: 100000,
    min: 10000,
    max: 1000000,
    step: 10000,
    unit: "$",
    severity: "breach",
  },
  {
    type: "inactivity_alert",
    name: "Activity Monitor",
    description: "The treasury must show transaction activity within this time window.",
    rationale: "Inactive treasuries may indicate lost keys, abandoned governance, or compromised signers. 7 days balances operational cadence with security.",
    paramKey: "threshold_hours",
    paramLabel: "Max hours inactive",
    defaultValue: 168,
    min: 24,
    max: 720,
    step: 24,
    unit: "hours",
    severity: "warning",
  },
  {
    type: "min_diversification",
    name: "Minimum Diversification",
    description: "The portfolio must hold at least this many distinct tokens.",
    rationale: "EU MiCA and MAS Singapore require diversified holdings to reduce systemic risk. Standard practice across all financial jurisdictions.",
    paramKey: "min_tokens",
    paramLabel: "Min token count",
    defaultValue: 3,
    min: 2,
    max: 10,
    step: 1,
    unit: "tokens",
    severity: "warning",
  },
  {
    type: "volatile_exposure",
    name: "Volatile Asset Exposure",
    description: "Non-stablecoin (volatile) assets cannot exceed this percentage of the portfolio.",
    rationale: "Limits exposure to market swings. Aligned with EU AIFMD reserve frameworks and prudential requirements from European and Asian regulators.",
    paramKey: "max_percent",
    paramLabel: "Max % volatile assets",
    defaultValue: 80,
    min: 30,
    max: 95,
    step: 5,
    unit: "%",
    severity: "warning",
  },
  {
    type: "min_treasury_value",
    name: "Minimum Treasury Value",
    description: "Total portfolio value must remain above this USD floor.",
    rationale: "Ensures operational solvency. Inspired by Basel III capital adequacy principles adopted by Japan FSA, Finansinspektionen (Sweden), and other regulators.",
    paramKey: "min_usd",
    paramLabel: "Min total USD value",
    defaultValue: 100000,
    min: 10000,
    max: 5000000,
    step: 10000,
    unit: "$",
    severity: "breach",
  },
  {
    type: "large_tx_ratio",
    name: "Relative Transaction Cap",
    description: "No single transaction should exceed this percentage of total portfolio value.",
    rationale: "AML/CFT compliance requires monitoring transactions relative to portfolio size. Required by FinCEN (US), FCA (UK), and FATF member regulators.",
    paramKey: "max_percent",
    paramLabel: "Max % of portfolio per tx",
    defaultValue: 15,
    min: 5,
    max: 50,
    step: 5,
    unit: "%",
    severity: "breach",
  },
  {
    type: "concentration_hhi",
    name: "Concentration Index (HHI)",
    description: "The Herfindahl-Hirschman Index measures portfolio concentration (0 = diversified, 10000 = single asset).",
    rationale: "HHI is the standard financial metric used by SEC, European Commission, and BaFin for measuring concentration risk in portfolios and markets.",
    paramKey: "max_hhi",
    paramLabel: "Max HHI score",
    defaultValue: 3000,
    min: 1500,
    max: 6000,
    step: 250,
    unit: "HHI",
    severity: "warning",
  },
];

export const SCENARIOS: Scenario[] = [
  {
    id: "compliant",
    title: "Well-Balanced Treasury",
    subtitle: "$2.1M, 25% stablecoins, diversified",
    tag: "Compliant",
    tagColor: "green",
    report: {
      safe_address: "0x849D...7e41 (example)",
      total_usd: 2100000,
      overall_status: "COMPLIANT",
      passed: 10,
      failed: 0,
      total_rules: 10,
      results: [
        { rule: "allocation_cap", name: "Single-Token Concentration Cap", description: "", rationale: "", passed: true, current_value: "28.5%", threshold: "30%", severity: "breach", detail: "Largest position is ETH at 28.5% — within the 30% cap" },
        { rule: "stablecoin_floor", name: "Stablecoin Minimum Floor", description: "", rationale: "", passed: true, current_value: "25.2%", threshold: "20%", severity: "breach", detail: "Stablecoins: $529,200 (25.2% of portfolio)" },
        { rule: "single_asset_cap", name: "Absolute Asset Value Cap", description: "", rationale: "", passed: true, current_value: "all within cap", threshold: "$500,000", severity: "warning", detail: "No single asset exceeds the $500,000 absolute cap" },
        { rule: "max_tx_size", name: "Transaction Size Limit", description: "", rationale: "", passed: true, current_value: "12 txs checked", threshold: "$100,000", severity: "breach", detail: "All 12 recent transactions within $100,000 cap" },
        { rule: "inactivity_alert", name: "Activity Monitor", description: "", rationale: "", passed: true, current_value: "36h ago", threshold: "168h", severity: "warning", detail: "Last transaction: 36 hours ago — well within 7-day window" },
        { rule: "min_diversification", name: "Minimum Diversification", description: "", rationale: "", passed: true, current_value: "5 tokens", threshold: "3 min", severity: "warning", detail: "Portfolio holds 5 distinct tokens" },
        { rule: "volatile_exposure", name: "Volatile Asset Exposure Cap", description: "", rationale: "", passed: true, current_value: "74.8%", threshold: "80%", severity: "warning", detail: "Volatile assets: $1,570,800 (74.8% of portfolio)" },
        { rule: "min_treasury_value", name: "Minimum Treasury Threshold", description: "", rationale: "", passed: true, current_value: "$2,100,000", threshold: "$100,000", severity: "breach", detail: "Total portfolio value: $2,100,000" },
        { rule: "large_tx_ratio", name: "Relative Transaction Cap", description: "", rationale: "", passed: true, current_value: "12 txs checked", threshold: "15%", severity: "breach", detail: "All 12 recent transactions within 15% of portfolio" },
        { rule: "concentration_hhi", name: "Portfolio Concentration Index", description: "", rationale: "", passed: true, current_value: "2180 (moderate)", threshold: "3000", severity: "warning", detail: "HHI score: 2180 (moderate)" },
      ],
      recommendations: [],
      ai_analysis: null,
    },
  },
  {
    id: "concentrated",
    title: "Over-Concentrated in ETH",
    subtitle: "$1.8M, 72% in a single token",
    tag: "High Risk",
    tagColor: "red",
    report: {
      safe_address: "0xA3f1...9c02 (example)",
      total_usd: 1800000,
      overall_status: "NON-COMPLIANT",
      passed: 5,
      failed: 5,
      total_rules: 10,
      results: [
        { rule: "allocation_cap", name: "Single-Token Concentration Cap", description: "", rationale: "", passed: false, current_value: "72.1%", threshold: "30%", severity: "breach", detail: "ETH is 72.1% of portfolio ($1,297,800) — exceeds 30% cap" },
        { rule: "stablecoin_floor", name: "Stablecoin Minimum Floor", description: "", rationale: "", passed: false, current_value: "8.3%", threshold: "20%", severity: "breach", detail: "Stablecoins: $149,400 (8.3% of portfolio) — below 20% floor" },
        { rule: "single_asset_cap", name: "Absolute Asset Value Cap", description: "", rationale: "", passed: false, current_value: "1 asset over cap", threshold: "$500,000", severity: "warning", detail: "Over cap: ETH: $1,297,800" },
        { rule: "max_tx_size", name: "Transaction Size Limit", description: "", rationale: "", passed: true, current_value: "8 txs checked", threshold: "$100,000", severity: "breach", detail: "All 8 recent transactions within $100,000 cap" },
        { rule: "inactivity_alert", name: "Activity Monitor", description: "", rationale: "", passed: true, current_value: "12h ago", threshold: "168h", severity: "warning", detail: "Last transaction: 12 hours ago" },
        { rule: "min_diversification", name: "Minimum Diversification", description: "", rationale: "", passed: false, current_value: "2 tokens", threshold: "3 min", severity: "warning", detail: "Portfolio holds 2 distinct tokens — below 3 minimum" },
        { rule: "volatile_exposure", name: "Volatile Asset Exposure Cap", description: "", rationale: "", passed: false, current_value: "91.7%", threshold: "80%", severity: "warning", detail: "Volatile assets: $1,650,600 (91.7% of portfolio) — exceeds 80% cap" },
        { rule: "min_treasury_value", name: "Minimum Treasury Threshold", description: "", rationale: "", passed: true, current_value: "$1,800,000", threshold: "$100,000", severity: "breach", detail: "Total portfolio value: $1,800,000" },
        { rule: "large_tx_ratio", name: "Relative Transaction Cap", description: "", rationale: "", passed: true, current_value: "8 txs checked", threshold: "15%", severity: "breach", detail: "All 8 recent transactions within 15% of portfolio" },
        { rule: "concentration_hhi", name: "Portfolio Concentration Index", description: "", rationale: "", passed: true, current_value: "5270 (concentrated)", threshold: "3000", severity: "warning", detail: "HHI score: 5270 (concentrated) — exceeds 3000 threshold" },
      ],
      recommendations: [
        { rule: "allocation_cap", action: "Rebalance by swapping a portion of ETH into stablecoins or diversified assets.", severity: "breach" },
        { rule: "stablecoin_floor", action: "Increase stablecoin holdings by converting volatile assets. Target USDC or DAI for maximum liquidity.", severity: "breach" },
        { rule: "single_asset_cap", action: "Reduce ETH position size. Consider dollar-cost averaging out over multiple transactions.", severity: "warning" },
        { rule: "min_diversification", action: "Add new token positions to diversify the portfolio.", severity: "warning" },
        { rule: "volatile_exposure", action: "Reduce volatile asset exposure by converting a portion into stablecoins.", severity: "warning" },
      ],
      ai_analysis: null,
    },
  },
  {
    id: "low-stable",
    title: "Low Stablecoin Reserves",
    subtitle: "$900K, only 5% stablecoins",
    tag: "Medium Risk",
    tagColor: "yellow",
    report: {
      safe_address: "0xD4e2...1b38 (example)",
      total_usd: 900000,
      overall_status: "NON-COMPLIANT",
      passed: 7,
      failed: 3,
      total_rules: 10,
      results: [
        { rule: "allocation_cap", name: "Single-Token Concentration Cap", description: "", rationale: "", passed: true, current_value: "29.8%", threshold: "30%", severity: "breach", detail: "Largest position is WBTC at 29.8% — just within the 30% cap" },
        { rule: "stablecoin_floor", name: "Stablecoin Minimum Floor", description: "", rationale: "", passed: false, current_value: "5.1%", threshold: "20%", severity: "breach", detail: "Stablecoins: $45,900 (5.1% of portfolio) — below 20% floor" },
        { rule: "single_asset_cap", name: "Absolute Asset Value Cap", description: "", rationale: "", passed: true, current_value: "all within cap", threshold: "$500,000", severity: "warning", detail: "No single asset exceeds the $500,000 absolute cap" },
        { rule: "max_tx_size", name: "Transaction Size Limit", description: "", rationale: "", passed: true, current_value: "5 txs checked", threshold: "$100,000", severity: "breach", detail: "All 5 recent transactions within $100,000 cap" },
        { rule: "inactivity_alert", name: "Activity Monitor", description: "", rationale: "", passed: true, current_value: "72h ago", threshold: "168h", severity: "warning", detail: "Last transaction: 72 hours ago" },
        { rule: "min_diversification", name: "Minimum Diversification", description: "", rationale: "", passed: true, current_value: "4 tokens", threshold: "3 min", severity: "warning", detail: "Portfolio holds 4 distinct tokens" },
        { rule: "volatile_exposure", name: "Volatile Asset Exposure Cap", description: "", rationale: "", passed: false, current_value: "94.9%", threshold: "80%", severity: "warning", detail: "Volatile assets: $854,100 (94.9% of portfolio) — exceeds 80% cap" },
        { rule: "min_treasury_value", name: "Minimum Treasury Threshold", description: "", rationale: "", passed: true, current_value: "$900,000", threshold: "$100,000", severity: "breach", detail: "Total portfolio value: $900,000" },
        { rule: "large_tx_ratio", name: "Relative Transaction Cap", description: "", rationale: "", passed: true, current_value: "5 txs checked", threshold: "15%", severity: "breach", detail: "All 5 recent transactions within 15% of portfolio" },
        { rule: "concentration_hhi", name: "Portfolio Concentration Index", description: "", rationale: "", passed: false, current_value: "2650 (concentrated)", threshold: "3000", severity: "warning", detail: "HHI score: 2650 (concentrated)" },
      ],
      recommendations: [
        { rule: "stablecoin_floor", action: "Increase stablecoin holdings by converting volatile assets. Target USDC or DAI for maximum liquidity.", severity: "breach" },
        { rule: "volatile_exposure", action: "Reduce volatile asset exposure by converting a portion into stablecoins.", severity: "warning" },
      ],
      ai_analysis: null,
    },
  },
  {
    id: "inactive",
    title: "Dormant Treasury",
    subtitle: "$450K, no activity in 30 days",
    tag: "Warning",
    tagColor: "yellow",
    report: {
      safe_address: "0x71B8...4e59 (example)",
      total_usd: 450000,
      overall_status: "NON-COMPLIANT",
      passed: 9,
      failed: 1,
      total_rules: 10,
      results: [
        { rule: "allocation_cap", name: "Single-Token Concentration Cap", description: "", rationale: "", passed: true, current_value: "24.2%", threshold: "30%", severity: "breach", detail: "No single token exceeds allocation cap" },
        { rule: "stablecoin_floor", name: "Stablecoin Minimum Floor", description: "", rationale: "", passed: true, current_value: "31.5%", threshold: "20%", severity: "breach", detail: "Stablecoins: $141,750 (31.5% of portfolio)" },
        { rule: "single_asset_cap", name: "Absolute Asset Value Cap", description: "", rationale: "", passed: true, current_value: "all within cap", threshold: "$500,000", severity: "warning", detail: "No single asset exceeds the $500,000 absolute cap" },
        { rule: "max_tx_size", name: "Transaction Size Limit", description: "", rationale: "", passed: true, current_value: "3 txs checked", threshold: "$100,000", severity: "breach", detail: "All 3 recent transactions within $100,000 cap" },
        { rule: "inactivity_alert", name: "Activity Monitor", description: "", rationale: "", passed: false, current_value: "720h ago", threshold: "168h", severity: "warning", detail: "Last transaction: 30 days ago — exceeds 168h threshold" },
        { rule: "min_diversification", name: "Minimum Diversification", description: "", rationale: "", passed: true, current_value: "4 tokens", threshold: "3 min", severity: "warning", detail: "Portfolio holds 4 distinct tokens" },
        { rule: "volatile_exposure", name: "Volatile Asset Exposure Cap", description: "", rationale: "", passed: true, current_value: "68.5%", threshold: "80%", severity: "warning", detail: "Volatile assets: $308,250 (68.5% of portfolio)" },
        { rule: "min_treasury_value", name: "Minimum Treasury Threshold", description: "", rationale: "", passed: true, current_value: "$450,000", threshold: "$100,000", severity: "breach", detail: "Total portfolio value: $450,000" },
        { rule: "large_tx_ratio", name: "Relative Transaction Cap", description: "", rationale: "", passed: true, current_value: "3 txs checked", threshold: "15%", severity: "breach", detail: "All 3 recent transactions within 15% of portfolio" },
        { rule: "concentration_hhi", name: "Portfolio Concentration Index", description: "", rationale: "", passed: true, current_value: "1920 (moderate)", threshold: "3000", severity: "warning", detail: "HHI score: 1920 (moderate)" },
      ],
      recommendations: [
        { rule: "inactivity_alert", action: "Verify signer access and confirm the treasury is actively governed. Schedule regular rebalancing transactions.", severity: "warning" },
      ],
      ai_analysis: null,
    },
  },
  {
    id: "solana-balanced",
    title: "Solana Treasury (Balanced)",
    subtitle: "$1.5M SOL + stablecoins",
    tag: "Compliant",
    tagColor: "green",
    chain: "solana",
    report: {
      safe_address: "9WzD...AWWM (Solana)",
      total_usd: 1500000,
      overall_status: "COMPLIANT",
      passed: 10,
      failed: 0,
      total_rules: 10,
      results: [
        { rule: "allocation_cap", name: "Single-Token Concentration Cap", description: "", rationale: "", passed: true, current_value: "26.7%", threshold: "30%", severity: "breach", detail: "Largest position is SOL at 26.7% — within the 30% cap" },
        { rule: "stablecoin_floor", name: "Stablecoin Minimum Floor", description: "", rationale: "", passed: true, current_value: "35.0%", threshold: "20%", severity: "breach", detail: "Stablecoins: $525,000 (35.0% of portfolio) — USDC + USDT" },
        { rule: "single_asset_cap", name: "Absolute Asset Value Cap", description: "", rationale: "", passed: true, current_value: "all within cap", threshold: "$500,000", severity: "warning", detail: "No single asset exceeds the $500,000 absolute cap" },
        { rule: "max_tx_size", name: "Transaction Size Limit", description: "", rationale: "", passed: true, current_value: "8 txs checked", threshold: "$100,000", severity: "breach", detail: "All 8 recent transactions within $100,000 cap" },
        { rule: "inactivity_alert", name: "Activity Monitor", description: "", rationale: "", passed: true, current_value: "4h ago", threshold: "168h", severity: "warning", detail: "Last transaction: 4 hours ago — very active" },
        { rule: "min_diversification", name: "Minimum Diversification", description: "", rationale: "", passed: true, current_value: "4 tokens", threshold: "3 min", severity: "warning", detail: "Portfolio holds 4 distinct tokens" },
        { rule: "volatile_exposure", name: "Volatile Asset Exposure Cap", description: "", rationale: "", passed: true, current_value: "65.0%", threshold: "80%", severity: "warning", detail: "Volatile assets: $975,000 (65.0% of portfolio)" },
        { rule: "min_treasury_value", name: "Minimum Treasury Threshold", description: "", rationale: "", passed: true, current_value: "$1,500,000", threshold: "$100,000", severity: "breach", detail: "Total portfolio value: $1,500,000" },
        { rule: "large_tx_ratio", name: "Relative Transaction Cap", description: "", rationale: "", passed: true, current_value: "8 txs checked", threshold: "15%", severity: "breach", detail: "All 8 recent transactions within 15% of portfolio" },
        { rule: "concentration_hhi", name: "Portfolio Concentration Index", description: "", rationale: "", passed: true, current_value: "2010 (moderate)", threshold: "3000", severity: "warning", detail: "HHI score: 2010 (moderate)" },
      ],
      recommendations: [],
      ai_analysis: null,
    },
  },
  {
    id: "solana-concentrated",
    title: "SOL-Heavy Portfolio",
    subtitle: "$800K, 85% in SOL",
    tag: "High Risk",
    tagColor: "red",
    chain: "solana",
    report: {
      safe_address: "DYw8...3kNz (Solana)",
      total_usd: 800000,
      overall_status: "NON-COMPLIANT",
      passed: 4,
      failed: 6,
      total_rules: 10,
      results: [
        { rule: "allocation_cap", name: "Single-Token Concentration Cap", description: "", rationale: "", passed: false, current_value: "85.0%", threshold: "30%", severity: "breach", detail: "SOL is 85.0% of portfolio ($680,000) — exceeds 30% cap" },
        { rule: "stablecoin_floor", name: "Stablecoin Minimum Floor", description: "", rationale: "", passed: false, current_value: "6.3%", threshold: "20%", severity: "breach", detail: "Stablecoins: $50,400 (6.3% of portfolio) — below 20% floor" },
        { rule: "single_asset_cap", name: "Absolute Asset Value Cap", description: "", rationale: "", passed: false, current_value: "1 asset over cap", threshold: "$500,000", severity: "warning", detail: "Over cap: SOL: $680,000" },
        { rule: "max_tx_size", name: "Transaction Size Limit", description: "", rationale: "", passed: true, current_value: "6 txs checked", threshold: "$100,000", severity: "breach", detail: "All 6 recent transactions within $100,000 cap" },
        { rule: "inactivity_alert", name: "Activity Monitor", description: "", rationale: "", passed: true, current_value: "18h ago", threshold: "168h", severity: "warning", detail: "Last transaction: 18 hours ago" },
        { rule: "min_diversification", name: "Minimum Diversification", description: "", rationale: "", passed: false, current_value: "2 tokens", threshold: "3 min", severity: "warning", detail: "Portfolio holds 2 distinct tokens — below 3 minimum" },
        { rule: "volatile_exposure", name: "Volatile Asset Exposure Cap", description: "", rationale: "", passed: false, current_value: "93.7%", threshold: "80%", severity: "warning", detail: "Volatile assets: $749,600 (93.7% of portfolio) — exceeds 80% cap" },
        { rule: "min_treasury_value", name: "Minimum Treasury Threshold", description: "", rationale: "", passed: true, current_value: "$800,000", threshold: "$100,000", severity: "breach", detail: "Total portfolio value: $800,000" },
        { rule: "large_tx_ratio", name: "Relative Transaction Cap", description: "", rationale: "", passed: true, current_value: "6 txs checked", threshold: "15%", severity: "breach", detail: "All 6 recent transactions within 15% of portfolio" },
        { rule: "concentration_hhi", name: "Portfolio Concentration Index", description: "", rationale: "", passed: false, current_value: "7260 (concentrated)", threshold: "3000", severity: "warning", detail: "HHI score: 7260 (concentrated) — exceeds 3000 threshold" },
      ],
      recommendations: [
        { rule: "allocation_cap", action: "Diversify by converting a portion of SOL into stablecoins or other assets.", severity: "breach" },
        { rule: "stablecoin_floor", action: "Increase stablecoin holdings. Target USDC on Solana for maximum liquidity.", severity: "breach" },
        { rule: "single_asset_cap", action: "Reduce SOL position size to stay within the $500,000 absolute cap.", severity: "warning" },
        { rule: "min_diversification", action: "Add new token positions to diversify the portfolio.", severity: "warning" },
        { rule: "volatile_exposure", action: "Reduce volatile asset exposure by converting a portion into stablecoins.", severity: "warning" },
      ],
      ai_analysis: null,
    },
  },
];
